In [6]:
ls

appearances.csv.gz   game_events.csv.gz     player_valuations.csv.gz
club_games.csv.gz    game_lineups.csv.gz    transfers.csv.gz
clubs.csv.gz         games.csv.gz           Untitled.ipynb
competitions.csv.gz  national_teams.csv.gz
countries.csv.gz     players.csv.gz

In [8]:
import pandas as pd

players = pd.read_csv("appearances.csv.gz")

players.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,76,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [9]:
import pandas as pd

players = pd.read_csv("club_games.csv.gz")

players.head()

,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
0,1026846,3449,2,NaN,Óscar Tabárez,3589,1,NaN,Jung-moo Huh,Home,1
1,1026846,3589,1,NaN,Jung-moo Huh,3449,2,NaN,Óscar Tabárez,Away,0
2,1026847,3437,3,NaN,Diego Maradona,6303,1,NaN,Javier Aguirre,Home,1
3,1026847,6303,1,NaN,Javier Aguirre,3437,3,NaN,Diego Maradona,Away,0
4,1027001,3441,2,NaN,Milovan Rajevac,3505,1,NaN,Bob Bradley,Away,1

In [10]:
import pandas as pd

players = pd.read_csv("clubs.csv.gz")

players.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris FC,FR1,NaN,27,27.2,14,51.9,7,Stade Jean Bouin,19904,€-25.00m,Stéphane Gilli,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.6,9,28.1,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
3,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,9,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
4,1005,us-lecce,US Lecce,IT1,NaN,39,23.8,36,92.3,10,Ettore Giardiniero,31559,+€3.35m,Eusebio Di Francesco,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...

In [11]:
import pandas as pd

players = pd.read_csv("competitions.csv.gz")

players.head()

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
0,A1,bundesliga,bundesliga,first_tier,domestic_league,127,Austria,A1,europa,12.0,https://www.transfermarkt.co.uk/bundesliga/sta...
1,AFAC,afc-asian-cup,afc-asian-cup,afc_asian_cup,national_team_competition,-1,NaN,NaN,asien,NaN,https://www.transfermarkt.co.uk/afc-asian-cup/...
2,AFCN,africa-cup-of-nations,africa-cup-of-nations,africa_cup_of_nations,national_team_competition,-1,NaN,NaN,afrika,NaN,https://www.transfermarkt.co.uk/africa-cup-of-...
3,ARG1,torneo-apertura,torneo-apertura,first_tier,domestic_league,9,Argentina,ARG1,amerika,30.0,https://www.transfermarkt.co.uk/torneo-apertur...
4,AUS1,a-league-men,a-league-men,first_tier,domestic_league,12,Australia,AUS1,asien,12.0,https://www.transfermarkt.co.uk/a-league-men/s...

In [12]:
import pandas as pd

players = pd.read_csv("countries.csv.gz")

players.head()

,country_id,country_name,country_code,confederation,total_clubs,total_players,average_age,url
0,10,Armenia,ARM1,europa,10,267,25.0,https://www.transfermarkt.co.uk/wettbewerbe/na...
1,100,North Macedonia,MAZ1,europa,12,298,25.4,https://www.transfermarkt.co.uk/wettbewerbe/na...
2,103,Malaysia,MYS1,asien,13,396,28.5,https://www.transfermarkt.co.uk/wettbewerbe/na...
3,104,Maldives,MLD1,asien,10,289,29.7,https://www.transfermarkt.co.uk/wettbewerbe/na...
4,106,Malta,MT1N,europa,12,297,27.0,https://www.transfermarkt.co.uk/wettbewerbe/na...

In [13]:
import pandas as pd

players = pd.read_csv("game_events.csv.gz")

players.head()

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
0,60d28dc455d299f5abdb65d7204fef40,2010-06-26,1026846,69,Cards,3589,South Korea,1772,"1. Yellow card , Foul",NaN,NaN
1,71280d139049475e02eb7627897da117,2010-06-26,1026846,38,Cards,3589,South Korea,27402,"1. Yellow card , Foul",NaN,NaN
2,dbb0d095a58423d8377d6b5b6b9f258f,2010-06-26,1026846,8,Goals,3449,Uruguay,44352,", Right-footed shot, 2. Tournament Goal Assist...",NaN,3408.0
3,6948606e52c10f6a2032ebe64355fe14,2010-06-26,1026846,80,Goals,3449,Uruguay,44352,", Right-footed shot, 3. Tournament Goal Assist...",NaN,72653.0
4,eb2ca121e9069fac2789c9e0be7cdbd3,2010-06-26,1026846,84,Substitutions,3449,Uruguay,44352,", Tactical",76213.0,NaN

In [14]:
import pandas as pd

players = pd.read_csv("game_lineups.csv.gz")

players.head()

/tmp/ipykernel_32227/3598165643.py:3: DtypeWarning: Columns (0: number) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv("game_lineups.csv.gz")

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

In [15]:
import pandas as pd

players = pd.read_csv("games.csv.gz")

players.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition

In [16]:
import pandas as pd

players = pd.read_csv("national_teams.csv.gz")

players.head()

,national_team_id,name,team_code,country_id,country_name,country_code,confederation,team_image_url,squad_size,average_age,foreigners_number,foreigners_percentage,total_market_value,coach_name,fifa_ranking,last_season,url
0,10521,San Marino,san-marino,144,San Marino,SMR1,UEFA,https://tmssl.akamaized.net//images/wappen/hom...,26,23.8,18,69.2,1250000.0,NaN,211,2025,https://www.transfermarkt.co.uk/san-marino/sta...
1,10533,Andorra,andorra,5,Andorra,AND1,UEFA,https://tmssl.akamaized.net//images/wappen/hom...,27,29.1,12,44.4,3910000.0,NaN,172,2025,https://www.transfermarkt.co.uk/andorra/starts...
2,11953,Montenegro,montenegro,216,Montenegro,MNE1,UEFA,https://tmssl.akamaized.net//images/wappen/hom...,28,28.0,25,89.3,69430000.0,NaN,80,2025,https://www.transfermarkt.co.uk/montenegro/sta...
3,13342,Guatemala,guatemala,58,Guatemala,GU1A,CONCACAF,https://tmssl.akamaized.net//images/wappen/hom...,23,25.8,9,39.1,7780000.0,NaN,97,2025,https://www.transfermarkt.co.uk/guatemala/star...
4,13497,Uganda,uganda,176,Uganda,UGL1,CAF,https://tmssl.akamaized.net//images/wappen/hom...,29,28.1,24,82.8,8750000.0,NaN,89,2025,https://www.transfermarkt.co.uk/uganda/startse...

In [17]:
import pandas as pd

players = pd.read_csv("players.csv.gz")

players.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus FC,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000.0,3000000.0

In [18]:
import pandas as pd

players = pd.read_csv("player_valuations.csv.gz")

players.head()

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057,BE1
1,342216,2001-07-20,100000,Unknown,1241,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126,TR1
3,6893,2003-12-15,900000,Galatasaray,984,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398,IT1

In [19]:
import pandas as pd

players = pd.read_csv("transfers.csv.gz")

players.head()

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli
1,645842,2028-02-02,27/28,6505,19684,Gimcheon Sangmu,Jeju SK,0.0,150000.0,Chan-gi An
2,677470,2028-02-02,27/28,6505,3535,Gimcheon Sangmu,Ulsan HD,0.0,400000.0,Yool Heo
3,709155,2028-02-02,27/28,6505,19684,Gimcheon Sangmu,Jeju SK,0.0,325000.0,Jae-hyeok Oh
4,728133,2028-02-02,27/28,6505,35759,Gimcheon Sangmu,Bucheon FC,0.0,175000.0,Sang-hyeok Lee

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display

In [3]:

def explore_table(path, head=5, top_values=5):
    """
    Quick profiling of a CSV/CSV.GZ table for Bronze -> Silver analysis.

    Shows:
      - sample rows
      - shape
      - inferred pandas dtypes
      - memory usage
      - null counts / percentages
      - duplicated rows
      - cardinality per column
      - candidate key columns
      - numeric summary
      - categorical summary
      - frequent values
    """

    path = Path(path)
    table_name = path.name.replace(".csv.gz", "").replace(".csv", "")

    print("=" * 100)
    print(f"TABLE: {table_name}")
    print("=" * 100)

    # low_memory=False avoids chunk-based mixed type inference warnings
    df = pd.read_csv(path, low_memory=False)

    # ------------------------------------------------------------------
    # 1. BASIC SAMPLE
    # ------------------------------------------------------------------
    print("\n[1] FIRST ROWS")
    display(df.head(head))

    # ------------------------------------------------------------------
    # 2. DIMENSIONS
    # ------------------------------------------------------------------
    print("\n[2] DIMENSIONS")
    print(f"Rows:    {len(df):,}")
    print(f"Columns: {df.shape[1]:,}")
    print(f"Cells:   {df.size:,}")

    memory_mb = df.memory_usage(deep=True).sum() / 1024**2
    print(f"Memory:  {memory_mb:,.2f} MB")

    # ------------------------------------------------------------------
    # 3. COLUMN TYPES
    # ------------------------------------------------------------------
    print("\n[3] COLUMN TYPES")

    types = pd.DataFrame({
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values
    })

    display(types)

    # ------------------------------------------------------------------
    # 4. NULLS + CARDINALITY
    # ------------------------------------------------------------------
    print("\n[4] NULLS AND CARDINALITY")

    profile = pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "non_null": df.notna().sum(),
        "null_count": df.isna().sum(),
        "null_pct": (df.isna().mean() * 100).round(2),
        "unique_count": df.nunique(dropna=True),
    })

    profile["unique_pct"] = (
        profile["unique_count"] / len(df) * 100
    ).round(2)

    profile = profile.sort_values(
        ["null_pct", "unique_count"],
        ascending=[False, False]
    )

    display(profile)

    # ------------------------------------------------------------------
    # 5. DUPLICATES
    # ------------------------------------------------------------------
    print("\n[5] DUPLICATES")

    duplicated_rows = df.duplicated().sum()

    print(f"Duplicated complete rows: {duplicated_rows:,}")
    print(
        f"Duplicated complete rows (%): "
        f"{duplicated_rows / len(df) * 100:.4f}%"
        if len(df)
        else "N/A"
    )

    if duplicated_rows:
        print("\nExample duplicated rows:")
        display(df[df.duplicated(keep=False)].head(10))

    # ------------------------------------------------------------------
    # 7. NUMERIC SUMMARY
    # ------------------------------------------------------------------
    numeric_cols = df.select_dtypes(include=np.number).columns

    print("\n[7] NUMERIC SUMMARY")

    if len(numeric_cols):
        display(
            df[numeric_cols]
            .describe()
            .T
            .round(2)
        )
    else:
        print("No numeric columns.")

    # ------------------------------------------------------------------
    # 8. TEXT / CATEGORICAL SUMMARY
    # ------------------------------------------------------------------
    categorical_cols = df.select_dtypes(
        include=["object", "string", "category"]
    ).columns

    print("\n[8] TEXT / CATEGORICAL SUMMARY")

    categorical_summary = []

    for col in categorical_cols:
        non_null = df[col].dropna()

        categorical_summary.append({
            "column": col,
            "non_null": len(non_null),
            "unique": non_null.nunique(),
            "avg_length": (
                non_null.astype(str).str.len().mean()
                if len(non_null)
                else np.nan
            ),
            "max_length": (
                non_null.astype(str).str.len().max()
                if len(non_null)
                else np.nan
            )
        })

    if categorical_summary:
        display(pd.DataFrame(categorical_summary))
    else:
        print("No text/categorical columns.")

    # ------------------------------------------------------------------
    # 9. MOST COMMON VALUES
    # ------------------------------------------------------------------
    print("\n[9] MOST COMMON VALUES")

    for col in categorical_cols:
        # Do not dump effectively unique fields such as URLs or hashes
        unique_ratio = df[col].nunique(dropna=True) / max(len(df), 1)

        if unique_ratio <= 0.20:
            print(f"\n--- {col} ---")
            display(
                df[col]
                .value_counts(dropna=False)
                .head(top_values)
                .rename("count")
                .to_frame()
            )

    # ------------------------------------------------------------------
    # 10. POTENTIAL DATE COLUMNS
    # ------------------------------------------------------------------
    print("\n[10] POSSIBLE DATE COLUMNS")

    date_candidates = [
        col for col in df.columns
        if "date" in col.lower()
        or col.lower().endswith("_at")
    ]

    date_rows = []

    for col in date_candidates:
        parsed = pd.to_datetime(df[col], errors="coerce")

        date_rows.append({
            "column": col,
            "original_dtype": str(df[col].dtype),
            "parseable": parsed.notna().sum(),
            "unparseable_non_null": (
                df[col].notna() & parsed.isna()
            ).sum(),
            "min_date": parsed.min(),
            "max_date": parsed.max()
        })

    if date_rows:
        display(pd.DataFrame(date_rows))
    else:
        print("No obvious date columns detected.")


    print("\n" + "=" * 100)

    return df

In [4]:
df = explore_table("appearances.csv.gz")

====================================================================================================
TABLE: appearances
====================================================================================================

[1] FIRST ROWS

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,76,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

[2] DIMENSIONS
Rows:    1,894,350
Columns: 13
Cells:   24,626,550
Memory:  260.89 MB

[3] COLUMN TYPES

                    column  dtype
0            appearance_id    str
1                  game_id  int64
2                player_id  int64
3           player_club_id  int64
4   player_current_club_id  int64
5                     date    str
6              player_name    str
7           competition_id    str
8             yellow_cards  int64
9                red_cards  int64
10                   goals  int64
11                 assists  int64
12          minutes_played  int64

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
appearance_id,str,1894350,0,0.0,1894350,100.00
game_id,int64,1894350,0,0.0,73426,3.88
player_id,int64,1894350,0,0.0,29531,1.56
player_name,str,1894348,2,0.0,28911,1.53
date,str,1894350,0,0.0,4108,0.22
player_club_id,int64,1894350,0,0.0,1231,0.06
player_current_club_id,int64,1894350,0,0.0,1148,0.06
minutes_played,int64,1894350,0,0.0,123,0.01
competition_id,str,1894350,0,0.0,48,0.00
goals,int64,1894350,0,0.0,7,0.00
assists,int64,1894350,0,0.0,7,0.00
yellow_cards,int64,1894350,0,0.0,3,0.00
red_cards,int64,1894350,0,0.0,2,0.00

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
game_id,1894350.0,3309904.60,766799.53,2211607.0,2609774.0,3210320.0,3909971.0,4868900.0
player_id,1894350.0,241233.87,225456.71,10.0,62457.0,175446.0,348298.0,1528441.0
player_club_id,1894350.0,3393.84,9376.20,1.0,289.0,826.0,2441.0,132877.0
player_current_club_id,1894350.0,5459.18,13883.10,-1.0,366.0,987.0,3060.0,138189.0
yellow_cards,1894350.0,0.14,0.36,0.0,0.0,0.0,0.0,2.0
red_cards,1894350.0,0.00,0.06,0.0,0.0,0.0,0.0,1.0
goals,1894350.0,0.10,0.33,0.0,0.0,0.0,0.0,6.0
assists,1894350.0,0.07,0.28,0.0,0.0,0.0,0.0,6.0
minutes_played,1894350.0,68.52,30.20,0.0,45.0,90.0,90.0,148.0

[8] TEXT / CATEGORICAL SUMMARY

           column  non_null   unique  avg_length  max_length
0   appearance_id   1894350  1894350   13.622782          15
1            date   1894350     4108   10.000000          10
2     player_name   1894348    28911   13.489830          34
3  competition_id   1894350       48    2.937855           4

[9] MOST COMMON VALUES

--- date ---

            count
date
2026-05-17   1931
2025-11-09   1915
2025-10-05   1807
2020-10-04   1795
2022-11-13   1747

--- player_name ---

             count
player_name
Danilo        1181
Paulinho      1062
Marcelo        970
João Pedro     844
Guilherme      797

--- competition_id ---

                 count
competition_id
IT1             155187
ES1             153877
GB1             149751
FR1             143395
TR1             132464

[10] POSSIBLE DATE COLUMNS

  column original_dtype  parseable  unparseable_non_null   min_date   max_date
0   date            str    1894350                     0 2012-07-03 2026-06-28

====================================================================================================

In [5]:
club_games = explore_table("club_games.csv.gz")

====================================================================================================
TABLE: club_games
====================================================================================================

[1] FIRST ROWS

,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
0,1026846,3449,2,NaN,Óscar Tabárez,3589,1,NaN,Jung-moo Huh,Home,1
1,1026846,3589,1,NaN,Jung-moo Huh,3449,2,NaN,Óscar Tabárez,Away,0
2,1026847,3437,3,NaN,Diego Maradona,6303,1,NaN,Javier Aguirre,Home,1
3,1026847,6303,1,NaN,Javier Aguirre,3437,3,NaN,Diego Maradona,Away,0
4,1027001,3441,2,NaN,Milovan Rajevac,3505,1,NaN,Bob Bradley,Away,1

[2] DIMENSIONS
Rows:    177,916
Columns: 11
Cells:   1,957,076
Memory:  20.38 MB

[3] COLUMN TYPES

                   column    dtype
0                 game_id    int64
1                 club_id    int64
2               own_goals    int64
3            own_position  float64
4        own_manager_name      str
5             opponent_id    int64
6          opponent_goals    int64
7       opponent_position  float64
8   opponent_manager_name      str
9                 hosting      str
10                 is_win    int64

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
own_position,float64,127162,50754,28.53,21,0.01
opponent_position,float64,127162,50754,28.53,21,0.01
own_manager_name,str,176228,1688,0.95,7031,3.95
opponent_manager_name,str,176228,1688,0.95,7031,3.95
game_id,int64,177916,0,0.00,88958,50.00
club_id,int64,177916,0,0.00,3274,1.84
opponent_id,int64,177916,0,0.00,3274,1.84
own_goals,int64,177916,0,0.00,18,0.01
opponent_goals,int64,177916,0,0.00,18,0.01
hosting,str,177916,0,0.00,2,0.00
is_win,int64,177916,0,0.00,2,0.00

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
game_id,177916.0,3393562.69,821280.23,25767.0,2640744.0,3254691.5,4121003.0,4868900.0
club_id,177916.0,5700.13,13323.19,1.0,368.0,1038.0,3592.0,134734.0
own_goals,177916.0,1.46,1.40,0.0,0.0,1.0,2.0,19.0
own_position,127162.0,9.20,5.28,1.0,5.0,9.0,13.0,21.0
opponent_id,177916.0,5700.13,13323.19,1.0,368.0,1038.0,3592.0,134734.0
opponent_goals,177916.0,1.46,1.40,0.0,0.0,1.0,2.0,19.0
opponent_position,127162.0,9.20,5.28,1.0,5.0,9.0,13.0,21.0
is_win,177916.0,0.39,0.49,0.0,0.0,0.0,1.0,1.0

[8] TEXT / CATEGORICAL SUMMARY

                  column  non_null  unique  avg_length  max_length
0       own_manager_name    176228    7031   13.835372          29
1  opponent_manager_name    176228    7031   13.835372          29
2                hosting    177916       2    4.000000           4

[9] MOST COMMON VALUES

--- own_manager_name ---

                  count
own_manager_name
NaN                1688
Diego Simeone       768
Pep Guardiola       721
Unai Emery          719
José Mourinho       640

--- opponent_manager_name ---

                       count
opponent_manager_name
NaN                     1688
Diego Simeone            768
Pep Guardiola            721
Unai Emery               719
José Mourinho            640

--- hosting ---

         count
hosting
Home     88958
Away     88958

[10] POSSIBLE DATE COLUMNS
No obvious date columns detected.

====================================================================================================

In [6]:
clubs = explore_table("clubs.csv.gz")

====================================================================================================
TABLE: clubs
====================================================================================================

[1] FIRST ROWS

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris FC,FR1,NaN,27,27.2,14,51.9,7,Stade Jean Bouin,19904,€-25.00m,Stéphane Gilli,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.6,9,28.1,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
3,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,9,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
4,1005,us-lecce,US Lecce,IT1,NaN,39,23.8,36,92.3,10,Ettore Giardiniero,31559,+€3.35m,Eusebio Di Francesco,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...

[2] DIMENSIONS
Rows:    796
Columns: 17
Cells:   13,532
Memory:  0.25 MB

[3] COLUMN TYPES

                     column    dtype
0                   club_id    int64
1                 club_code      str
2                      name      str
3   domestic_competition_id      str
4        total_market_value  float64
5                squad_size    int64
6               average_age  float64
7         foreigners_number    int64
8     foreigners_percentage  float64
9     national_team_players    int64
10             stadium_name      str
11            stadium_seats    int64
12      net_transfer_record      str
13               coach_name      str
14              last_season    int64
15                 filename      str
16                      url      str

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
total_market_value,float64,0,796,100.00,0,0.00
coach_name,str,403,393,49.37,395,49.62
foreigners_percentage,float64,736,60,7.54,279,35.05
average_age,float64,758,38,4.77,84,10.55
club_id,int64,796,0,0.00,796,100.00
club_code,str,796,0,0.00,796,100.00
name,str,796,0,0.00,796,100.00
url,str,796,0,0.00,796,100.00
stadium_name,str,796,0,0.00,760,95.48
stadium_seats,int64,796,0,0.00,658,82.66
net_transfer_record,str,796,0,0.00,482,60.55
squad_size,int64,796,0,0.00,43,5.40
foreigners_number,int64,796,0,0.00,33,4.15
domestic_competition_id,str,796,0,0.00,32,4.02
national_team_players,int64,796,0,0.00,24,3.02
last_season,int64,796,0,0.00,14,1.76
filename,str,796,0,0.00,14,1.76

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
club_id,796.0,9010.48,17250.00,3.0,602.5,2296.5,7425.25,118373.0
total_market_value,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
squad_size,796.0,26.78,8.29,0.0,25.0,28.0,31.00,50.0
average_age,758.0,25.46,2.45,0.0,24.5,25.6,26.70,30.1
foreigners_number,796.0,10.55,6.69,0.0,5.0,10.0,15.00,36.0
foreigners_percentage,736.0,40.04,20.14,2.4,24.0,39.4,54.68,100.0
national_team_players,796.0,3.92,4.58,0.0,0.0,2.0,6.00,24.0
stadium_seats,796.0,24269.77,17484.45,0.0,10800.0,20019.0,32290.25,87523.0
last_season,796.0,2023.39,3.23,2012.0,2024.0,2025.0,2025.00,2025.0

[8] TEXT / CATEGORICAL SUMMARY

                    column  non_null  unique  avg_length  max_length
0                club_code       796     796   14.396985          39
1                     name       796     796   16.415829          63
2  domestic_competition_id       796      32    3.218593           4
3             stadium_name       796     760   18.688442          50
4      net_transfer_record       796     482    5.967337           9
5               coach_name       403     395   13.674938          23
6                 filename       796      14   52.000000          52
7                      url       796     796   69.194724          95

[9] MOST COMMON VALUES

--- domestic_competition_id ---

                         count
domestic_competition_id
TR1                         43
IT1                         39
UKR1                        39
GB1                         37
FR1                         36

--- filename ---

                                                    count
filename
../data/raw/transfermarkt-scraper/2025/clubs.js...    548
../data/raw/transfermarkt-scraper/2024/clubs.js...     70
../data/raw/transfermarkt-scraper/2023/clubs.js...     23
../data/raw/transfermarkt-scraper/2022/clubs.js...     19
../data/raw/transfermarkt-scraper/2017/clubs.js...     17

[10] POSSIBLE DATE COLUMNS
No obvious date columns detected.

====================================================================================================

In [7]:
competitions = explore_table("competitions.csv.gz")

====================================================================================================
TABLE: competitions
====================================================================================================

[1] FIRST ROWS

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
0,A1,bundesliga,bundesliga,first_tier,domestic_league,127,Austria,A1,europa,12.0,https://www.transfermarkt.co.uk/bundesliga/sta...
1,AFAC,afc-asian-cup,afc-asian-cup,afc_asian_cup,national_team_competition,-1,NaN,NaN,asien,NaN,https://www.transfermarkt.co.uk/afc-asian-cup/...
2,AFCN,africa-cup-of-nations,africa-cup-of-nations,africa_cup_of_nations,national_team_competition,-1,NaN,NaN,afrika,NaN,https://www.transfermarkt.co.uk/africa-cup-of-...
3,ARG1,torneo-apertura,torneo-apertura,first_tier,domestic_league,9,Argentina,ARG1,amerika,30.0,https://www.transfermarkt.co.uk/torneo-apertur...
4,AUS1,a-league-men,a-league-men,first_tier,domestic_league,12,Australia,AUS1,asien,12.0,https://www.transfermarkt.co.uk/a-league-men/s...

[2] DIMENSIONS
Rows:    65
Columns: 11
Cells:   715
Memory:  0.01 MB

[3] COLUMN TYPES

                  column    dtype
0         competition_id      str
1       competition_code      str
2                   name      str
3               sub_type      str
4                   type      str
5             country_id    int64
6           country_name      str
7   domestic_league_code      str
8          confederation      str
9            total_clubs  float64
10                   url      str

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
total_clubs,float64,50,15,23.08,7,10.77
country_name,str,53,12,18.46,31,47.69
domestic_league_code,str,53,12,18.46,31,47.69
competition_id,str,65,0,0.00,65,100.00
url,str,65,0,0.00,65,100.00
competition_code,str,65,0,0.00,62,95.38
name,str,65,0,0.00,62,95.38
country_id,int64,65,0,0.00,32,49.23
sub_type,str,65,0,0.00,16,24.62
type,str,65,0,0.00,5,7.69
confederation,str,65,0,0.00,5,7.69

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

             count   mean    std   min   25%   50%    75%    max
country_id    65.0  86.49  69.71  -1.0  19.0  75.0  146.0  215.0
total_clubs   50.0  17.16   3.86  10.0  16.0  18.0   19.5   30.0

[8] TEXT / CATEGORICAL SUMMARY

                 column  non_null  unique  avg_length  max_length
0        competition_id        65      65    3.323077           4
1      competition_code        65      62   15.753846          39
2                  name        65      62   15.753846          39
3              sub_type        65      16   13.061538          33
4                  type        65       5   12.938462          25
5          country_name        53      31    7.377358          14
6  domestic_league_code        53      31    3.094340           4
7         confederation        65       5    5.969231           7
8                   url        65      65   75.000000          98

[9] MOST COMMON VALUES

--- type ---

                           count
type
domestic_league               31
other                         16
domestic_cup                  10
national_team_competition      5
international_cup              3

--- confederation ---

               count
confederation
europa            53
asien              5
amerika            5
afrika             1
fifa               1

[10] POSSIBLE DATE COLUMNS
No obvious date columns detected.

====================================================================================================

In [9]:
countries = explore_table("countries.csv.gz")

====================================================================================================
TABLE: countries
====================================================================================================

[1] FIRST ROWS

,country_id,country_name,country_code,confederation,total_clubs,total_players,average_age,url
0,10,Armenia,ARM1,europa,10,267,25.0,https://www.transfermarkt.co.uk/wettbewerbe/na...
1,100,North Macedonia,MAZ1,europa,12,298,25.4,https://www.transfermarkt.co.uk/wettbewerbe/na...
2,103,Malaysia,MYS1,asien,13,396,28.5,https://www.transfermarkt.co.uk/wettbewerbe/na...
3,104,Maldives,MLD1,asien,10,289,29.7,https://www.transfermarkt.co.uk/wettbewerbe/na...
4,106,Malta,MT1N,europa,12,297,27.0,https://www.transfermarkt.co.uk/wettbewerbe/na...

[2] DIMENSIONS
Rows:    124
Columns: 8
Cells:   992
Memory:  0.02 MB

[3] COLUMN TYPES

          column    dtype
0     country_id    int64
1   country_name      str
2   country_code      str
3  confederation      str
4    total_clubs    int64
5  total_players    int64
6    average_age  float64
7            url      str

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
country_id,int64,124,0,0.0,124,100.00
country_name,str,124,0,0.0,124,100.00
country_code,str,124,0,0.0,124,100.00
url,str,124,0,0.0,124,100.00
total_players,int64,124,0,0.0,105,84.68
average_age,float64,124,0,0.0,46,37.10
total_clubs,int64,124,0,0.0,14,11.29
confederation,str,124,0,0.0,4,3.23

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

               count    mean     std   min     25%    50%     75%    max
country_id     124.0  105.38   64.53   2.0   48.75  101.5  155.50  266.0
total_clubs    124.0   14.24    4.68   6.0   10.75   14.0   16.00   36.0
total_players  124.0  405.04  150.51   1.0  300.75  389.0  490.25  921.0
average_age    124.0   26.23    1.32  22.7   25.48   26.2   27.02   31.8

[8] TEXT / CATEGORICAL SUMMARY

          column  non_null  unique  avg_length  max_length
0   country_name       124     124    8.080645          20
1   country_code       124     124    3.693548           4
2  confederation       124       4    5.903226           7
3            url       124     124   67.467742          68

[9] MOST COMMON VALUES

--- confederation ---

               count
confederation
europa            54
asien             35
amerika           23
afrika            12

[10] POSSIBLE DATE COLUMNS
No obvious date columns detected.

====================================================================================================

In [10]:
game_events = explore_table("game_events.csv.gz")

====================================================================================================
TABLE: game_events
====================================================================================================

[1] FIRST ROWS

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
0,60d28dc455d299f5abdb65d7204fef40,2010-06-26,1026846,69,Cards,3589,South Korea,1772,"1. Yellow card , Foul",NaN,NaN
1,71280d139049475e02eb7627897da117,2010-06-26,1026846,38,Cards,3589,South Korea,27402,"1. Yellow card , Foul",NaN,NaN
2,dbb0d095a58423d8377d6b5b6b9f258f,2010-06-26,1026846,8,Goals,3449,Uruguay,44352,", Right-footed shot, 2. Tournament Goal Assist...",NaN,3408.0
3,6948606e52c10f6a2032ebe64355fe14,2010-06-26,1026846,80,Goals,3449,Uruguay,44352,", Right-footed shot, 3. Tournament Goal Assist...",NaN,72653.0
4,eb2ca121e9069fac2789c9e0be7cdbd3,2010-06-26,1026846,84,Substitutions,3449,Uruguay,44352,", Tactical",76213.0,NaN

[2] DIMENSIONS
Rows:    1,274,469
Columns: 11
Cells:   14,019,159
Memory:  214.44 MB

[3] COLUMN TYPES

              column    dtype
0      game_event_id      str
1               date      str
2            game_id    int64
3             minute    int64
4               type      str
5            club_id    int64
6          club_name      str
7          player_id    int64
8        description      str
9       player_in_id  float64
10  player_assist_id  float64

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
player_assist_id,float64,188278,1086191,85.23,30356,2.38
player_in_id,float64,630547,643922,50.52,67926,5.33
description,str,1181312,93157,7.31,8930,0.70
game_event_id,str,1274469,0,0.00,1274469,100.00
game_id,int64,1274469,0,0.00,88813,6.97
player_id,int64,1274469,0,0.00,74555,5.85
date,str,1274469,0,0.00,4443,0.35
club_name,str,1274469,0,0.00,3439,0.27
club_id,int64,1274469,0,0.00,3170,0.25
minute,int64,1274469,0,0.00,121,0.01
type,str,1274469,0,0.00,4,0.00

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
game_id,1274469.0,3478265.73,824066.58,25767.0,2718920.0,3433588.0,4312000.0,4868900.0
minute,1274469.0,62.09,23.40,-1.0,46.0,67.0,80.0,120.0
club_id,1274469.0,5835.52,13645.97,1.0,368.0,1038.0,3699.0,134732.0
player_id,1274469.0,291249.50,261196.68,10.0,81532.0,216443.0,417346.0,1522779.0
player_in_id,630547.0,350209.23,295263.01,10.0,112935.0,272930.0,514256.0,1564116.0
player_assist_id,188278.0,261103.05,241388.43,10.0,70114.0,188656.0,373916.0,1516900.0

[8] TEXT / CATEGORICAL SUMMARY

          column  non_null   unique  avg_length  max_length
0  game_event_id   1274469  1274469   32.000000          32
1           date   1274469     4443   10.000000          10
2           type   1274469        4    8.994945          13
3      club_name   1274469     3439   13.598827          38
4    description   1181312     8930   25.485653         100

[9] MOST COMMON VALUES

--- date ---

            count
date
2025-08-31   1917
2025-11-01   1904
2025-09-27   1884
2025-11-09   1865
2025-10-25   1829

--- type ---

                count
type
Substitutions  631339
Cards          381753
Goals          247803
Shootout        13574

--- club_name ---

                    count
club_name
FC Barcelona         6341
Real Madrid          6290
Atlético de Madrid   5970
Sevilla FC           5970
Bayern Munich        5641

--- description ---

                         count
description
, Tactical              403833
NaN                      93157
1. Yellow card  , Foul   85119
, Not reported           75264
1. Yellow card           48076

[10] POSSIBLE DATE COLUMNS

  column original_dtype  parseable  unparseable_non_null   min_date   max_date
0   date            str    1274469                     0 2006-06-09 2026-07-06

====================================================================================================

In [11]:
game_lineups = explore_table("game_lineups.csv.gz")

====================================================================================================
TABLE: game_lineups
====================================================================================================

[1] FIRST ROWS

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

[2] DIMENSIONS
Rows:    3,179,016
Columns: 10
Cells:   31,790,160
Memory:  496.26 MB

[3] COLUMN TYPES

            column  dtype
0  game_lineups_id    str
1             date    str
2          game_id  int64
3        player_id  int64
4          club_id  int64
5      player_name    str
6             type    str
7         position    str
8           number    str
9     team_captain  int64

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
game_lineups_id,str,3179016,0,0.0,3179016,100.00
player_id,int64,3179016,0,0.0,114893,3.61
player_name,str,3179016,0,0.0,111045,3.49
game_id,int64,3179016,0,0.0,81197,2.55
date,str,3179016,0,0.0,3967,0.12
club_id,int64,3179016,0,0.0,3144,0.10
number,str,3179016,0,0.0,169,0.01
position,str,3179013,3,0.0,18,0.00
type,str,3179016,0,0.0,2,0.00
team_captain,int64,3179016,0,0.0,2,0.00

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
game_id,3179016.0,3512883.60,781462.79,2317258.0,2764360.75,3446038.0,4295563.0,4868900.0
player_id,3179016.0,314757.17,280053.58,10.0,92899.00,236995.0,450936.0,1564118.0
club_id,3179016.0,5701.49,13380.46,1.0,368.00,1022.0,3563.0,134734.0
team_captain,3179016.0,0.05,0.21,0.0,0.00,0.0,0.0,1.0

[8] TEXT / CATEGORICAL SUMMARY

            column  non_null   unique  avg_length  max_length
0  game_lineups_id   3179016  3179016   32.000000          32
1             date   3179016     3967   10.000000          10
2      player_name   3179016   111045   13.571791          35
3             type   3179016        2   13.240642          15
4         position   3179013       18   12.834540          18
5           number   3179016      169    1.694868           3

[9] MOST COMMON VALUES

--- date ---

            count
date
2025-09-27   4947
2025-11-01   4685
2025-11-09   4579
2025-10-25   4457
2025-08-31   4385

--- player_name ---

             count
player_name
Danilo        1380
Paulinho      1332
João Pedro    1134
Guilherme     1071
Marcelo       1020

--- type ---

                   count
type
starting_lineup  1780759
substitutes      1398257

--- position ---

                     count
position
Centre-Back         551970
Centre-Forward      394661
Goalkeeper          357844
Central Midfield    329361
Defensive Midfield  279364

--- number ---

         count
number
7       114994
1       114864
8       114795
10      113874
11      110605

[10] POSSIBLE DATE COLUMNS

  column original_dtype  parseable  unparseable_non_null   min_date   max_date
0   date            str    3179016                     0 2013-07-02 2026-07-06

====================================================================================================

In [12]:
games = explore_table("games.csv.gz")

====================================================================================================
TABLE: games
====================================================================================================

[1] FIRST ROWS

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition

[2] DIMENSIONS
Rows:    88,958
Columns: 23
Cells:   2,046,034
Memory:  35.41 MB

[3] COLUMN TYPES

                    column    dtype
0                  game_id    int64
1           competition_id      str
2                   season    int64
3                    round      str
4                     date      str
5             home_club_id    int64
6             away_club_id    int64
7          home_club_goals    int64
8          away_club_goals    int64
9       home_club_position  float64
10      away_club_position  float64
11  home_club_manager_name      str
12  away_club_manager_name      str
13                 stadium      str
14              attendance  float64
15                 referee      str
16                     url      str
17     home_club_formation      str
18     away_club_formation      str
19          home_club_name      str
20          away_club_name      str
21               aggregate      str
22        competition_type      str

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
home_club_position,float64,63581,25377,28.53,21,0.02
away_club_position,float64,63581,25377,28.53,21,0.02
attendance,float64,78155,10803,12.14,33301,37.43
home_club_formation,str,80758,8200,9.22,57,0.06
away_club_formation,str,80885,8073,9.08,68,0.08
competition_type,str,87744,1214,1.36,5,0.01
home_club_manager_name,str,88114,844,0.95,6137,6.90
away_club_manager_name,str,88114,844,0.95,5756,6.47
referee,str,88280,678,0.76,3135,3.52
stadium,str,88716,242,0.27,2968,3.34
home_club_name,str,88872,86,0.10,2901,3.26
away_club_name,str,88922,36,0.04,2600,2.92
game_id,int64,88958,0,0.00,88958,100.00
url,str,88958,0,0.00,88958,100.00
date,str,88958,0,0.00,4445,5.00
home_club_id,int64,88958,0,0.00,2980,3.35
away_club_id,int64,88958,0,0.00,2634,2.96
round,str,88958,0,0.00,128,0.14
aggregate,str,88958,0,0.00,119,0.13
competition_id,str,88958,0,0.00,70,0.08
season,int64,88958,0,0.00,18,0.02
away_club_goals,int64,88958,0,0.00,18,0.02
home_club_goals,int64,88958,0,0.00,16,0.02

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
game_id,88958.0,3393562.69,821282.54,25767.0,2640744.25,3254691.5,4121002.75,4868900.0
season,88958.0,2019.04,4.25,2005.0,2015.00,2019.0,2023.00,2025.0
home_club_id,88958.0,5963.32,13894.14,1.0,369.00,1041.0,3709.00,134734.0
away_club_id,88958.0,5436.94,12721.28,2.0,368.00,1032.0,3508.00,134734.0
home_club_goals,88958.0,1.60,1.42,0.0,1.00,1.0,2.00,15.0
away_club_goals,88958.0,1.33,1.36,0.0,0.00,1.0,2.00,19.0
home_club_position,63581.0,9.11,5.27,1.0,5.00,9.0,13.00,21.0
away_club_position,63581.0,9.29,5.29,1.0,5.00,9.0,14.00,21.0
attendance,78155.0,18282.46,17922.47,1.0,4418.50,12350.0,26353.00,99354.0

[8] TEXT / CATEGORICAL SUMMARY

                    column  non_null  unique  avg_length  max_length
0           competition_id     88958      70    3.011477           4
1                    round     88958     128   12.210313          28
2                     date     88958    4445   10.000000          10
3   home_club_manager_name     88114    6137   13.841217          28
4   away_club_manager_name     88114    5756   13.829528          29
5                  stadium     88716    2968   17.618693          54
6                  referee     88280    3135   15.061679          41
7                      url     88958   88958   82.432923         125
8      home_club_formation     80758      57    9.212573          15
9      away_club_formation     80885      68    9.161130          33
10          home_club_name     88872    2901   14.917916          63
11          away_club_name     88922    2600   14.913216          63
12               aggregate     88958     119    3.001450           5
13        competition_type     87744       5   13.848377          25

[9] MOST COMMON VALUES

--- competition_id ---

                count
competition_id
GB1              5320
ES1              5320
IT1              5320
FR1              4997
TR1              4618

--- round ---

              count
round
First Round    3355
Second Round   2597
2. Matchday    1966
1. Matchday    1964
11. Matchday   1957

--- date ---

            count
date
2025-09-27    132
2025-08-31    118
2025-11-09    116
2025-10-25    115
2025-11-01    115

--- home_club_manager_name ---

                        count
home_club_manager_name
NaN                       844
Diego Simeone             374
Pep Guardiola             356
Unai Emery                352
Brendan Rodgers           318

--- away_club_manager_name ---

                        count
away_club_manager_name
NaN                       844
Diego Simeone             394
Unai Emery                367
Pep Guardiola             365
José Mourinho             324

--- stadium ---

                       count
stadium
Olimpico di Roma         718
Giuseppe Meazza          697
Luigi Ferraris           496
AFAS Stadion             436
Marcantonio Bentegodi    369

--- referee ---

                  count
referee
NaN                 678
Anthony Taylor      553
Michael Oliver      546
Danny Makkelie      483
Serdar Gözübüyük    429

--- home_club_formation ---

                     count
home_club_formation
4-2-3-1              25851
4-3-3 Attacking      12596
NaN                   8200
4-4-2 double 6        7149
4-1-4-1               4392

--- away_club_formation ---

                     count
away_club_formation
4-2-3-1              25190
4-3-3 Attacking      12384
NaN                   8073
4-4-2 double 6        6618
4-1-4-1               4561

--- home_club_name ---

                 count
home_club_name
Real Madrid        403
FC Barcelona       395
Chelsea FC         383
Juventus FC        382
Manchester City    380

--- away_club_name ---

                    count
away_club_name
Real Madrid           406
FC Barcelona          405
Atlético de Madrid    395
Sevilla FC            390
Manchester City       384

--- aggregate ---

           count
aggregate
1:1         8958
1:0         8451
2:1         7493
0:1         6721
2:0         6573

--- competition_type ---

                   count
competition_type
domestic_league    63382
domestic_cup       12904
other               7599
international_cup   3117
NaN                 1214

[10] POSSIBLE DATE COLUMNS

  column original_dtype  parseable  unparseable_non_null   min_date   max_date
0   date            str      88958                     0 2006-06-09 2026-07-06

====================================================================================================

In [13]:
national_teams = explore_table("national_teams.csv.gz")

====================================================================================================
TABLE: national_teams
====================================================================================================

[1] FIRST ROWS

,national_team_id,name,team_code,country_id,country_name,country_code,confederation,team_image_url,squad_size,average_age,foreigners_number,foreigners_percentage,total_market_value,coach_name,fifa_ranking,last_season,url
0,10521,San Marino,san-marino,144,San Marino,SMR1,UEFA,https://tmssl.akamaized.net//images/wappen/hom...,26,23.8,18,69.2,1250000.0,NaN,211,2025,https://www.transfermarkt.co.uk/san-marino/sta...
1,10533,Andorra,andorra,5,Andorra,AND1,UEFA,https://tmssl.akamaized.net//images/wappen/hom...,27,29.1,12,44.4,3910000.0,NaN,172,2025,https://www.transfermarkt.co.uk/andorra/starts...
2,11953,Montenegro,montenegro,216,Montenegro,MNE1,UEFA,https://tmssl.akamaized.net//images/wappen/hom...,28,28.0,25,89.3,69430000.0,NaN,80,2025,https://www.transfermarkt.co.uk/montenegro/sta...
3,13342,Guatemala,guatemala,58,Guatemala,GU1A,CONCACAF,https://tmssl.akamaized.net//images/wappen/hom...,23,25.8,9,39.1,7780000.0,NaN,97,2025,https://www.transfermarkt.co.uk/guatemala/star...
4,13497,Uganda,uganda,176,Uganda,UGL1,CAF,https://tmssl.akamaized.net//images/wappen/hom...,29,28.1,24,82.8,8750000.0,NaN,89,2025,https://www.transfermarkt.co.uk/uganda/startse...

[2] DIMENSIONS
Rows:    124
Columns: 17
Cells:   2,108
Memory:  0.04 MB

[3] COLUMN TYPES

                   column    dtype
0        national_team_id    int64
1                    name      str
2               team_code      str
3              country_id    int64
4            country_name      str
5            country_code      str
6           confederation      str
7          team_image_url      str
8              squad_size    int64
9             average_age  float64
10      foreigners_number    int64
11  foreigners_percentage  float64
12     total_market_value  float64
13             coach_name  float64
14           fifa_ranking    int64
15            last_season    int64
16                    url      str

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
coach_name,float64,0,124,100.00,0,0.00
foreigners_percentage,float64,116,8,6.45,71,57.26
total_market_value,float64,120,4,3.23,120,96.77
confederation,str,123,1,0.81,6,4.84
national_team_id,int64,124,0,0.00,124,100.00
name,str,124,0,0.00,124,100.00
team_code,str,124,0,0.00,124,100.00
country_id,int64,124,0,0.00,124,100.00
country_name,str,124,0,0.00,124,100.00
country_code,str,124,0,0.00,124,100.00
team_image_url,str,124,0,0.00,124,100.00
url,str,124,0,0.00,124,100.00
fifa_ranking,int64,124,0,0.00,123,99.19
average_age,float64,124,0,0.00,54,43.55
foreigners_number,int64,124,0,0.00,29,23.39
squad_size,int64,124,0,0.00,12,9.68
last_season,int64,124,0,0.00,1,0.81

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
national_team_id,124.0,7.705930e+03,7.025090e+03,3262.0,3463.50,3685.5,1.338075e+04,53982.0
country_id,124.0,1.053800e+02,6.453000e+01,2.0,48.75,101.5,1.555000e+02,266.0
squad_size,124.0,2.531000e+01,1.940000e+00,19.0,24.00,26.0,2.600000e+01,33.0
average_age,124.0,2.687000e+01,1.640000e+00,21.0,26.10,26.9,2.800000e+01,30.5
foreigners_number,124.0,1.407000e+01,8.190000e+00,0.0,7.00,14.5,2.200000e+01,30.0
foreigners_percentage,116.0,5.896000e+01,2.870000e+01,3.8,34.60,59.3,8.850000e+01,100.0
total_market_value,120.0,1.308911e+08,1.937724e+08,350000.0,8132500.00,34375000.0,1.935500e+08,947000000.0
coach_name,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fifa_ranking,124.0,7.967000e+01,5.683000e+01,1.0,31.75,68.5,1.232500e+02,211.0
last_season,124.0,2.025000e+03,0.000000e+00,2025.0,2025.00,2025.0,2.025000e+03,2025.0

[8] TEXT / CATEGORICAL SUMMARY

           column  non_null  unique  avg_length  max_length
0            name       124     124    8.080645          20
1       team_code       124     124    8.177419          20
2    country_name       124     124    8.080645          20
3    country_code       124     124    3.693548           4
4   confederation       123       6    4.373984           8
5  team_image_url       124     124   87.137097          88
6             url       124     124   63.459677          75

[9] MOST COMMON VALUES

--- confederation ---

               count
confederation
UEFA              54
AFC               32
CONCACAF          13
CAF               12
CONMEBOL          10

[10] POSSIBLE DATE COLUMNS
No obvious date columns detected.

====================================================================================================

In [14]:
player_valuations = explore_table("player_valuations.csv.gz")

====================================================================================================
TABLE: player_valuations
====================================================================================================

[1] FIRST ROWS

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057,BE1
1,342216,2001-07-20,100000,Unknown,1241,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126,TR1
3,6893,2003-12-15,900000,Galatasaray,984,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398,IT1

[2] DIMENSIONS
Rows:    656,301
Columns: 6
Cells:   3,937,806
Memory:  47.04 MB

[3] COLUMN TYPES

                                column  dtype
0                            player_id  int64
1                                 date    str
2                  market_value_in_eur  int64
3                    current_club_name    str
4                      current_club_id  int64
5  player_club_domestic_competition_id    str

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
player_club_domestic_competition_id,str,563328,92973,14.17,32,0.00
player_id,int64,656301,0,0.00,41528,6.33
current_club_name,str,656301,0,0.00,8055,1.23
date,str,656301,0,0.00,5749,0.88
current_club_id,int64,656301,0,0.00,5424,0.83
market_value_in_eur,int64,656301,0,0.00,426,0.06

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
player_id,656301.0,299884.35,267660.43,10.0,79723.0,226146.0,437842.0,1523289.0
market_value_in_eur,656301.0,2290092.74,6721808.73,0.0,200000.0,500000.0,1500000.0,200000000.0
current_club_id,656301.0,6707.55,13766.74,1.0,430.0,1237.0,6079.0,136215.0

[8] TEXT / CATEGORICAL SUMMARY

,column,non_null,unique,avg_length,max_length
0,date,656301,5749,10.000000,10
1,current_club_name,656301,8055,14.283531,52
2,player_club_domestic_competition_id,563328,32,3.063278,4

[9] MOST COMMON VALUES

--- date ---

            count
date
2020-04-08  12111
2015-07-01   4207
2016-07-15   2979
2026-06-04   2300
2023-12-19   1949

--- current_club_name ---

                   count
current_club_name
Without Club        4375
Unknown             3199
Trabzonspor         1490
Galatasaray         1477
Fenerbahce          1454

--- player_club_domestic_competition_id ---

                                     count
player_club_domestic_competition_id
NaN                                  92973
IT1                                  50413
TR1                                  47666
ES1                                  37561
L1                                   37049

[10] POSSIBLE DATE COLUMNS

  column original_dtype  parseable  unparseable_non_null   min_date   max_date
0   date            str     656301                     0 2000-01-20 2026-06-12

====================================================================================================

In [15]:
players = explore_table("players.csv.gz")

====================================================================================================
TABLE: players
====================================================================================================

[1] FIRST ROWS

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus FC,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000.0,3000000.0

[2] DIMENSIONS
Rows:    50,149
Columns: 26
Cells:   1,303,874
Memory:  24.04 MB

[3] COLUMN TYPES

                                  column    dtype
0                              player_id    int64
1                             first_name      str
2                              last_name      str
3                                   name      str
4                            last_season    int64
5                        current_club_id    int64
6                            player_code      str
7                       country_of_birth      str
8                          city_of_birth      str
9                 country_of_citizenship      str
10                         date_of_birth      str
11                          sub_position      str
12                              position      str
13                                  foot      str
14                          height_in_cm  float64
15              contract_expiration_date      str
16                            agent_name      str
17                             image_url      str
18                    international_caps  float64
19                   international_goals  float64
20              current_national_team_id  float64
21                                   url      str
22  current_club_domestic_competition_id      str
23                     current_club_name      str
24                   market_value_in_eur  float64
25           highest_market_value_in_eur  float64

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
current_national_team_id,float64,3260,46889,93.50,123,0.25
international_caps,float64,19356,30793,61.40,159,0.32
international_goals,float64,19356,30793,61.40,68,0.14
agent_name,str,26853,23296,46.45,3954,7.88
contract_expiration_date,str,31580,18569,37.03,241,0.48
highest_market_value_in_eur,float64,41528,8621,17.19,206,0.41
market_value_in_eur,float64,41528,8621,17.19,121,0.24
foot,str,44256,5893,11.75,3,0.01
country_of_birth,str,44264,5885,11.74,211,0.42
city_of_birth,str,44541,5608,11.18,12335,24.60
height_in_cm,float64,45784,4365,8.70,58,0.12
first_name,str,46985,3164,6.31,10800,21.54
current_club_name,str,47163,2986,5.95,793,1.58
current_club_domestic_competition_id,str,47163,2986,5.95,32,0.06
sub_position,str,49563,586,1.17,13,0.03
country_of_citizenship,str,49880,269,0.54,202,0.40
date_of_birth,str,50100,49,0.10,10359,20.66
player_id,int64,50149,0,0.00,50149,100.00
url,str,50149,0,0.00,50149,100.00
name,str,50149,0,0.00,48825,97.36
player_code,str,50149,0,0.00,48738,97.19
image_url,str,50149,0,0.00,41061,81.88
last_name,str,50149,0,0.00,33876,67.55
current_club_id,int64,50149,0,0.00,1852,3.69
last_season,int64,50149,0,0.00,14,0.03
position,str,50149,0,0.00,5,0.01

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
player_id,50149.0,512784.46,386401.07,10.0,186848.0,426944.0,801420.0,1555760.0
last_season,50149.0,2021.67,4.25,2012.0,2018.0,2024.0,2025.0,2025.0
current_club_id,50149.0,8547.64,17501.46,2.0,501.0,1496.0,6890.0,142301.0
height_in_cm,45784.0,182.00,7.43,17.0,177.0,182.0,187.0,210.0
international_caps,19356.0,11.37,18.99,0.0,1.0,4.0,12.0,233.0
international_goals,19356.0,1.18,4.16,0.0,0.0,0.0,1.0,146.0
current_national_team_id,3260.0,9230.51,6614.21,3262.0,3590.0,6133.0,14165.0,53982.0
market_value_in_eur,41528.0,1511049.29,5854556.45,10000.0,100000.0,275000.0,700000.0,200000000.0
highest_market_value_in_eur,41528.0,3450773.45,9347394.39,10000.0,300000.0,750000.0,2500000.0,200000000.0

[8] TEXT / CATEGORICAL SUMMARY

,column,non_null,unique,avg_length,max_length
0,first_name,46985,10800,6.018559,20
1,last_name,50149,33876,7.071288,23
2,name,50149,48825,13.647032,34
3,player_code,50149,48738,13.645935,35
4,country_of_birth,44264,211,7.543805,30
5,city_of_birth,44541,12335,11.404212,58
6,country_of_citizenship,49880,202,7.398436,24
7,date_of_birth,50100,10359,19.000000,19
8,sub_position,49563,13,12.847648,18
9,position,50149,5,7.682267,10
10,foot,44256,3,4.710525,5
11,contract_expiration_date,31580,241,19.000000,19
12,agent_name,26853,3954,11.439914,20
13,image_url,50149,41061,79.318750,91
14,url,50149,50149,67.615725,89
15,current_club_domestic_competition_id,47163,32,3.157751,4
16,current_club_name,47163,793,15.915548,63

[9] MOST COMMON VALUES

--- country_of_birth ---

                  count
country_of_birth
NaN                5885
France             2714
Brazil             2642
Spain              2348
England            2099

--- country_of_citizenship ---

                        count
country_of_citizenship
Brazil                   2736
Spain                    2289
Italy                    2075
France                   1974
England                  1762

--- sub_position ---

                    count
sub_position
Centre-Back          8766
Centre-Forward       6749
Goalkeeper           5828
Central Midfield     5498
Defensive Midfield   4123

--- position ---

            count
position
Defender    15961
Midfield    14272
Attack      13502
Goalkeeper   5828
Missing       586

--- foot ---

       count
foot
right  31445
left   11000
NaN     5893
both    1811

--- contract_expiration_date ---

                          count
contract_expiration_date
NaN                       18569
2027-06-30 00:00:00        4852
2023-06-30 00:00:00        4066
2028-06-30 00:00:00        3830
2026-06-30 00:00:00        3124

--- agent_name ---

              count
agent_name
NaN           23296
CAA Stellar     541
THE·TEAM        538
ProStar         434
CAA Base Ltd    431

--- current_club_domestic_competition_id ---

                                      count
current_club_domestic_competition_id
TR1                                    3375
IT1                                    3200
NaN                                    2986
GR1                                    2624
PO1                                    2590

--- current_club_name ---

                   count
current_club_name
NaN                 2986
Kilmarnock FC        204
Motherwell FC        188
Dundee FC            187
Antalyaspor          181

[10] POSSIBLE DATE COLUMNS

,column,original_dtype,parseable,unparseable_non_null,min_date,max_date
0,date_of_birth,str,50100,0,1968-07-31,2011-02-23
1,contract_expiration_date,str,31580,0,2000-05-31,2035-06-30

====================================================================================================

In [16]:
transfers = explore_table("transfers.csv.gz")

====================================================================================================
TABLE: transfers
====================================================================================================

[1] FIRST ROWS

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli
1,645842,2028-02-02,27/28,6505,19684,Gimcheon Sangmu,Jeju SK,0.0,150000.0,Chan-gi An
2,677470,2028-02-02,27/28,6505,3535,Gimcheon Sangmu,Ulsan HD,0.0,400000.0,Yool Heo
3,709155,2028-02-02,27/28,6505,19684,Gimcheon Sangmu,Jeju SK,0.0,325000.0,Jae-hyeok Oh
4,728133,2028-02-02,27/28,6505,35759,Gimcheon Sangmu,Bucheon FC,0.0,175000.0,Sang-hyeok Lee

[2] DIMENSIONS
Rows:    175,165
Columns: 10
Cells:   1,751,650
Memory:  21.79 MB

[3] COLUMN TYPES

                column    dtype
0            player_id    int64
1        transfer_date      str
2      transfer_season      str
3         from_club_id    int64
4           to_club_id    int64
5       from_club_name      str
6         to_club_name      str
7         transfer_fee  float64
8  market_value_in_eur  float64
9          player_name      str

[4] NULLS AND CARDINALITY

,dtype,non_null,null_count,null_pct,unique_count,unique_pct
market_value_in_eur,float64,107005,68160,38.91,191,0.11
transfer_fee,float64,113639,61526,35.12,1503,0.86
player_id,int64,175165,0,0.00,23379,13.35
player_name,str,175165,0,0.00,23036,13.15
from_club_name,str,175165,0,0.00,18285,10.44
from_club_id,int64,175165,0,0.00,17408,9.94
to_club_name,str,175165,0,0.00,14086,8.04
to_club_id,int64,175165,0,0.00,13208,7.54
transfer_date,str,175165,0,0.00,5634,3.22
transfer_season,str,175165,0,0.00,35,0.02

[5] DUPLICATES
Duplicated complete rows: 0
Duplicated complete rows (%): 0.0000%

[7] NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
player_id,175165.0,505230.24,312933.58,2989.0,256866.0,452164.0,700031.0,1545443.0
from_club_id,175165.0,21072.17,27801.58,1.0,1084.0,9259.0,31098.0,142714.0
to_club_id,175165.0,16527.06,24383.72,1.0,865.0,6107.0,21082.0,142487.0
transfer_fee,113639.0,739835.97,4245002.94,0.0,0.0,0.0,0.0,222000000.0
market_value_in_eur,107005.0,1753553.92,4714252.50,10000.0,200000.0,425000.0,1200000.0,180000000.0

[8] TEXT / CATEGORICAL SUMMARY

            column  non_null  unique  avg_length  max_length
0    transfer_date    175165    5634   10.000000          10
1  transfer_season    175165      35    5.000000           5
2   from_club_name    175165   18285   10.893266          34
3     to_club_name    175165   14086   10.631719          34
4      player_name    175165   23036   13.502406          34

[9] MOST COMMON VALUES

--- transfer_date ---

               count
transfer_date
2022-07-01      4232
2021-07-01      3981
2019-07-01      3971
2018-07-01      3783
2023-07-01      3659

--- transfer_season ---

                 count
transfer_season
23/24            17379
24/25            16686
22/23            16386
25/26            15676
21/22            15045

--- from_club_name ---

                count
from_club_name
Without Club     2490
Unknown           877
Inter             329
Genoa             315
Olympiacos        315

--- to_club_name ---

              count
to_club_name
Without Club   3785
Olympiacos      355
Inter           354
Genoa           346
Chelsea         316

--- player_name ---

             count
player_name
João Pedro      84
Dudu            70
Eduardo         64
Juninho         53
Guilherme       49

[10] POSSIBLE DATE COLUMNS

,column,original_dtype,parseable,unparseable_non_null,min_date,max_date
0,transfer_date,str,175165,0,1993-07-01,2030-06-30

====================================================================================================